### PR TITLE
Finalize lending modal

### PR DESCRIPTION
**Pull request by nanderv**

### CODE REVIEW

**Comment by nanderv** [comment]
Depends on #584 being merged

**Comment by KylianvD** [comment]
Looks great, but there seems to be one relevant oversight: going member>browse for>book gives a modal, going book>lend>finish lending does not.
The error modal appears to have no styling, but that's not a problem because nobody should ever see the thing.
Additionally, "No special case for active member for item type Comic" is printed to the terminal very, very often when, for an active member with a current membership, you "browse catalog for" and search for "la.

**Comment by nanderv** [comment]
> Looks great, but there seems to be one relevant oversight: going member>browse for>book gives a modal, going book>lend>finish lending does not. The error modal appears to have no styling, but that's not a problem because nobody should ever see the thing. Additionally, "No special case for active member for item type Comic" is printed to the terminal very, very often (1012 times I think?) when, for an active member with a current membership, you "browse catalog for" and search for "la.

I fixed the first thing (added extra htmx tags).

Which error modal lacks styling? The new 'cannot lend' page should have similar styling to other pages. Can be triggered by blacklisting a member while just before finalizing a lending.

For the latter one, there's a missing config setting in the config_lendingsettings table. The system runs perfectly fine without (using the non-active member lendingsettings as a fallback) but it's throwing log statements for it.

**Review by KylianvD — APPROVED** [review]
To answer the question: cannot_lend_hx.html does not have a header/footer/etc. like the other modals, which makes it look like it has less styling. But, that's not an issue because it is an error message which nobody should see and is very clear as is.

**Pull request merged**
